# permissions for end users to edit ceoslabdevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ceoslabdevice-editor-role
rules:
- apiGroups:
  - ceoslab.arista.com
  resources:
  - ceoslabdevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ceoslab.arista.com
  resources:
  - ceoslabdevices/status
  verbs:
  - get
