# permissions for end users to view ceoslabdevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ceoslabdevice-viewer-role
rules:
- apiGroups:
  - aristanetworks.com.my.domain
  resources:
  - ceoslabdevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aristanetworks.com.my.domain
  resources:
  - ceoslabdevices/status
  verbs:
  - get
